### ISSUE TITLE
mvn package error

### ISSUE THREAD

**Issue by RichardLiu0926** [JpressProjects/jpress#11]
[ERROR] Failed to execute goal on project jpress-web: Could not resolve dependencies for project io.jpress:jpress-web:war:1.0: The following artifacts could not be resolved: io.jpress:jpress-utils:jar:1.0, io.jpress:jpress-db-api:jar:1.0, io.jpress:jpress-db-mysql:jar:1.0, io.jpress:jpress-oauth2:jar:1.0, io.jpress:jpress-message:jar:1.0, io.jpress:jpress-search-api:jar:1.0, io.jpress:jpress-search-dbsimple:jar:1.0, io.jpress:jpress-consts:jar:1.0, io.jpress:jpress-model:jar:  0, io.jpress:jpress-addon:jar:1.0, io.jpress:jpress-web-template-jblog:war:1.0, io.jpress:jpress-web-template-the3:war:1.0: Could not find artifact io.jpress:jpress-utils:jar:1.0 in central (https://repo.maven.apache.org/maven2) -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException

**Comment by JpressProjects** [comment]
需要在 jpress 根目录执行“mvn package”命令
