### ISSUE TITLE
初始化向导中，最好能自动创建数据库，而不是要事先手动创建

### ISSUE THREAD

**Issue by xmpilot** [JpressProjects/jpress#112]

**Comment by 70852** [comment]
如果这样的话，你是还需要使用拥有建库权限的数据库用户，这样稳妥一些。
个人觉得可以这里是一个可选项，默认是使用可创建库的数据库用户，自动创建库，如果打上勾又有一个可输入的框输入库名，这样就合理了

**Comment by tabris233** [comment]
居然要自己建表。。。。 docker下也是。。。。   我不相信以作者的水平经验想不到不能自行建表的体验的有多差，，，
