### ISSUE TITLE
安装后一直没有跳转到首页，重启tomcat后出现错误

### ISSUE THREAD

**Issue by kevinhwq** [JpressProjects/jpress#12]
安装后一直没有跳转到首页，重启tomcat后出现错误：
![image](https://cloud.githubusercontent.com/assets/4221055/16755583/eaea02b8-4830-11e6-85cb-44ca8b9a6577.png)

**Comment by kevinhwq** [comment]
tomcat7.0.47+mysql 5.6

**Comment by icnws** [comment]
我用的没有问题啊，阿里云的服务器
你有没有将数据库配置文件改成db.properties，刚开始我的是因为这个原因无法正常使用

**Comment by 656469722** [comment]
我用新浪云也不行，安装后不跳转主页，重启后报502 Bad Gateway错误

**Comment by kevinhwq** [comment]
用新的jpress-web-0.2.5.1.war可以启动了，但出现锟斤拷乱码，server.xml加了URIEncoding="UTF-8"并没有用。怎么破？

![image](https://cloud.githubusercontent.com/assets/4221055/17501952/41435434-5e16-11e6-91a7-bd870468c57d.png)

**Comment by BoxMod** [comment]
chown -R www.www /data/wwwroot/
find /data/wwwroot/ -type d -exec chmod 755 {} \;
find /data/wwwroot/ -type f -exec chmod 644 {} \;
