### ISSUE TITLE
docker 安装问题

### ISSUE THREAD

**Issue by xingchenpro** [JPressProjects/jpress#145]
操作系统：CentOS 7.3
问题：
重启 docker 后，打开页面空白，重启容器也无法恢复。
需要删除数据库重新 run 数据库才能恢复。
查看容器日志，发现报错
`
021-01-29 01:36:22.561 ERROR io.jboot.web.handler.JbootActionHandler - io.jpress.web.install.InstallController.index() : /install
java.lang.RuntimeException: File not found : /opt/jpress/webapp/WEB-INF/install/views/step1.html

java.lang.NullPointerException: template is null
	at io.jpress.core.template.TemplateManager.setCurrentTemplate(TemplateManager.java:169)
	......
`
希望作者修复，谢谢

**Comment by JPressProjects** [comment]
无法复现
