### ISSUE TITLE
There is a storage XSS vulnerability in the template module

### ISSUE THREAD

**Issue by HyCXSS** [JPressProjects/jpress#152]
There is a storage XSS vulnerability in the template module.
The figure shows the setting interface of template management, which is used to describe the left part of the home page.
URL: `http://localhost:8080/admin/template/setting`
![](https://raw.githubusercontent.com/HyCXSS/IMG/main/1.png)

After inputting the payload in the figure above, any user entering the home page will trigger XSS vulnerability.
![](https://raw.githubusercontent.com/HyCXSS/IMG/main/2.png)

However, if hackers enter the background by means of weak password and add XSS code, they can easily cause great harm: Hijacking cookies, obtaining sensitive information, phishing and so on.

Similarly, there is a storage XSS vulnerability in commodity tag management, which can be successfully triggered on the commodity page
![](https://raw.githubusercontent.com/HyCXSS/IMG/main/3.png)

**Comment by JPressProjects** [comment]
这不是问题，后台本身就允许编辑代码。
