### ISSUE TITLE
jpress后台存在命令执行漏洞-恶意插件

### ISSUE THREAD

**Issue by Er1cccc** [JPressProjects/jpress#167]
# 审计过程

jpress后台提供了插件安装功能，在`io.jpress.web.admin._AddonController`的`doUploadAndInstall`方法，该方法的作用是先处理文件上传，然后进行插件安装

![image-20211221123337325](https://user-images.githubusercontent.com/64583215/148674957-2226ab5b-61d5-4990-8d30-d4113b50cba6.png)

文件上传的步骤略，直接看安装部分

![image-20211221123838727](https://user-images.githubusercontent.com/64583215/148674972-0eb9b370-6a0a-465f-a5b4-66838fdbdf26.png)

跟进`AddonManager.me().install(newAddonFile)`方法，在这个方法中，先调用了一下`AddonUtil.readAddonInfo`读取插件信息

![image-20211221124437123](https://user-images.githubusercontent.com/64583215/148674988-4d50cdac-5a23-4912-890f-5b60979960c4.png)

跟进`AddonUtil.readAddonInfo`，在这个方法里面会创建一个类加载器来加载插件里的类

![image-20211221124722280](https://user-images.githubusercontent.com/64583215/148674994-58ef4b28-ed4e-4632-9dbe-13cf4f55c29f.png)

跟进`classLoader.load()`，这个方法的作用就是先加载类，然后把不同的类进行归类，Controller归到一起，Interceptor归到一起

先加载类

![image-20211221124855501](https://user-images.githubusercontent.com/64583215/148675006-f46aa434-af02-4cd2-94c5-7d2a2838d0f6.png)

然后根据类的功能进行归类，把他们分别添加到了addonInfo的特定字段当中

![image-20211221125020872](https://user-images.githubusercontent.com/64583215/148675020-1be3b720-7928-4a35-b6d2-aeeca69625fc.png)

接下来在处理请求时就会利用到这些controller

# 攻击步骤

1. 使用弱口令进入后台

2. 上传恶意插件[jpress-addon-helloworld-4.0.jar](http://121.5.40.245:8081/jpress-addon-helloworld-4.0.jar)

![image-20211220230337451](https://user-images.githubusercontent.com/64583215/148675093-7c63c5df-ca74-4c6e-8cd0-dcfbeb678b61.png)

3. 安装完成查看一下插件是否存在

![image-20211220230357826](https://user-images.githubusercontent.com/64583215/148674928-68ab2b7d-745e-449b-8bf5-51856e481761.png)

4. 利用插件实现命令执行，访问http://127.0.0.1/helloworld/?command=dir

![image-20211220230448114](https://user-images.githubusercontent.com/64583215/148674937-b0d2dec1-f573-4fba-8274-aa7def7f2d18.png)

**Comment by JPressProjects** [comment]
不处理这个问题，原因是：
1、必须获得 JPress 的后台登录地址，虽然有默认的登录地址，但是可配置成其他复杂的地址
2、拥有登录地址后，必须有管理员的账号和密码，这种一般只有设置了弱密码，或者管理员主动泄漏。
3、安装了 恶意 的插件


而目前 Java 行业凡是对于可以安装插件的产品来讲，都是无法避免这个问题的。这个需要网站管理提高安全意识、设置复杂的登录地址和登录账号密码，不轻易安装不认可的插件即可解决。这种由于安全意识造成的问题，并非软件问题。
