### ISSUE TITLE
安装过后出现乱码

### ISSUE THREAD

**Issue by zhuriddd** [JpressProjects/jpress#17]
![image](https://cloud.githubusercontent.com/assets/20652429/17505731/c05a3f3e-5e35-11e6-9db7-7bab6054f0c0.png)

**Comment by czy1994** [comment]
我也遇到这个问题

**Comment by zhuriddd** [comment]
感觉应该是页面编码的问题，创建完成后页面会缓存在tomca下的temp文件夹中，使用的是utf-8进行的编码，但页面应该是统一使用iso8859-1进行的统一编码，然后通过这个进行转码，这时候可能就会出问题了。这些都是个人的想法有可能不对。

**Comment by mozhuwanjieDEV** [comment]
Downloading: http://repo.knet.cn/content/groups/public/io/jpress/jpress-utils/1.0/jpress-utils-1.0.pom
[WARNING] The POM for io.jpress:jpress-utils:jar:1.0 is missing, no dependency information available
Downloading: http://repo.knet.cn/content/groups/public/io/jpress/jpress-db-api/1.0/jpress-db-api-1.0.pom
[WARNING] The POM for io.jpress:jpress-db-api:jar:1.0 is missing, no dependency information available
Downloading: http://repo.knet.cn/content/groups/public/io/jpress/jpress-db-mysql/1.0/jpress-db-mysql-1.0.pom
[WARNING] The POM for io.jpress:jpress-db-mysql:jar:1.0 is missing, no dependency information available
Downloading: http://repo.knet.cn/content/groups/public/io/jpress/jpress-oauth2/1.0/jpress-oauth2-1.0.pom
[WARNING] The POM for io.jpress:jpress-oauth2:jar:1.0 is missing, no dependency information available
Downloading: http://repo.knet.cn/content/groups/public/io/jpress/jpress-message/1.0/jpress-message-1.0.pom
[WARNING] The POM for io.jpress:jpress-message:jar:1.0 is missing, no dependency information available
Downloading: http://repo.knet.cn/content/groups/public/io/jpress/jpress-search-api/1.0/jpress-search-api-1.0.pom
[WARNING] The POM for io.jpress:jpress-search-api:jar:1.0 is missing, no dependency information available
Downloading: http://repo.knet.cn/content/groups/public/io/jpress/jpress-search-dbsimple/1.0/jpress-search-dbsimple-1.0.pom
[WARNING] The POM for io.jpress:jpress-search-dbsimple:jar:1.0 is missing, no dependency information available
Downloading: http://repo.knet.cn/content/groups/public/io/jpress/jpress-consts/1.0/jpress-consts-1.0.pom
[WARNING] The POM for io.jpress:jpress-consts:jar:1.0 is missing, no dependency information available
Downloading: http://repo.knet.cn/content/groups/public/io/jpress/jpress-model/1.0/jpress-model-1.0.pom
[WARNING] The POM for io.jpress:jpress-model:jar:1.0 is missing, no dependency information available
Downloading: http://repo.knet.cn/content/groups/public/io/jpress/jpress-web-core/1.0/jpress-web-core-1.0.pom
[WARNING] The POM for io.jpress:jpress-web-core:jar:1.0 is missing, no dependency information available
Downloading: http://repo.knet.cn/content/groups/public/io/jpress/jpress-web-template-jblog/1.0/jpress-web-template-jblog-1.0.pom
[WARNING] The POM for io.jpress:jpress-web-template-jblog:war:1.0 is missing, no dependency information available
Downloading: http://repo.knet.cn/content/groups/public/io/jpress/jpress-web-template-the3/1.0/jpress-web-template-the3-1.0.pom
[WARNING] The POM for io.jpress:jpress-web-template-the3:war:1.0 is missing, no dependency information available

**Comment by JpressProjects** [comment]
谢谢反馈，文字乱码已经修复；
