### ISSUE TITLE
jpress前台存在任意文件上传漏洞

### ISSUE THREAD

**Issue by Er1cccc** [JPressProjects/jpress#173]
# 审计过程

jpress框架在安装好之后默认用户注册登录功能

![image-20211223165121108](https://user-images.githubusercontent.com/64583215/149648410-e4919048-d9f9-4cff-bebf-8c0f281a21ae.png)

我们可以随意注册一个用户进入到个人主页

![image-20211223165157532](https://user-images.githubusercontent.com/64583215/149648469-5547d443-2284-4e05-9c58-5df77c4977eb.png)

在个人主页有文件上传接口，先尝试上传一个html文件，用bp抓包之后发现上传失败了

![image-20211223171050527](https://user-images.githubusercontent.com/64583215/149648415-6ac19e94-0589-42b7-8d8a-0df5c5edc4b6.png)

再来看看成功的回显，这次把后缀改成jpg，成功时会直接回显图片的路径

![image-20211223165710851](https://user-images.githubusercontent.com/64583215/149648420-6c3e1c61-cef5-4e74-aabf-56362c07a4e9.png)

来看后端的代码，在`io.jpress.web.commons.controller.AttachmentController#upload`。首先，在51行调用了`getFile`，获取我们上传的文件

![image-20211223165923799](https://user-images.githubusercontent.com/64583215/149648422-61054ee7-3034-4ac2-8dd3-7a3386965fb2.png)

跟进`getFile`，发现这个方法首先获取了上传的文件数组，然后返回第0个元素，说明我们是可以上传多个文件的

![image-20211223170016557](https://user-images.githubusercontent.com/64583215/149648473-789a5a0f-1d39-4159-acfe-c198595798ad.png)

在执行完`getFile`之后，可以看到，我们上传的文件已经被保存到了临时文件目录，也就是attachment目录下。

![image-20211223170136985](https://user-images.githubusercontent.com/64583215/149648490-30c3190d-6cf3-47b6-93b8-4a4b6b853bc0.png)

紧接着，在65行，判断了文件是否合法，不合法就删除

![image-20211223170226545](https://user-images.githubusercontent.com/64583215/149648436-81baf60d-5894-4e00-8c1b-faed1fb55985.png)

看到这里应该能想到问题。我们可以上传多个文件（都会存储到临时文件目录），但是最后只检查了第一个文件，如果不合法就删除，其他文件是不会受影响的。

于是我们尝试上传多个文件，直接在bp当中改数据包，加多一个文件

![image-20211223171236280](https://user-images.githubusercontent.com/64583215/149648439-bc1e32e9-1233-4789-8a72-2412b509f6db.png)

发包之后发现，1.html成功上传到了attachment目录，成功绕过了后缀名限制，实现了任意文件上传

![image-20211223171252559](https://user-images.githubusercontent.com/64583215/149648444-7346a5e8-d5b1-4c1a-9962-a905ce8208e8.png)

**Comment by JPressProjects** [comment]
新版本已修复。
