### ISSUE TITLE
内容页图片路径问题

### ISSUE THREAD

**Issue by itRyze** [JpressProjects/jpress#18]
首先我的项目是tomcat的webapps下的blog文件夹，
项目部署到tomcat后，必须配置tomcat的主页为这个项目，才能在内容页正确显示上传的头像
查看网页源码可以看到图片路径是web容器根目录+attachment......，显然中间没有blog这个项目文件夹名，当我把tomcat的主页配置成这个项目时，图片就正常显示了。这应该是个小BUG吧

**Comment by JpressProjects** [comment]
找个问题早就修复，下载最新版本即可。
