### ISSUE TITLE
页面有特殊字符>时，显示不对

### ISSUE THREAD

**Issue by hxsam** [JpressProjects/jpress#27]
在页面中 输入 l >22 这个，在body 和meta之间有个这样的显示 “&lt;body class="blog-body"&gt;22"&gt;
&lt;meta http-equiv="Content-Type" content="text/html; charset=utf-8"&gt;

当为普通文章输入 l >22 这个没问题。

![image](https://cloud.githubusercontent.com/assets/15061658/18986435/561cdd66-872f-11e6-8923-d5835c8e64c2.png)

**Comment by PriSt7** [comment]
所以文章中的xml格式的代码也会出问题，
