### ISSUE TITLE
第三方QQ登录认证返回后拉取用户信息有错误

### ISSUE THREAD

**Issue by rancedxk** [JpressProjects/jpress#28]
类io.jpress.oauth2.connector.QQConnector

_78行代码_
`return httpString.substring(httpString.lastIndexOf(":") + 2, httpString.lastIndexOf("\"") - 1);`
_应改为_
`return httpString.substring(httpString.lastIndexOf(":") + 2, httpString.lastIndexOf("\""));`

_109行代码_
`user.setOpenId(json.getString("openid"));`
_应改为_
`user.setOpenId(openId);`

**Comment by JpressProjects** [comment]
已经修复，谢谢反馈。
