### ISSUE TITLE
切换主题后找不到新建的页面

### ISSUE THREAD

**Issue by mamacmm** [JpressProjects/jpress#3]
切换到 the3  主题（貌似在程序里面直接切换不管用，只能先修改配置文件）后，发现刚刚新建的页面找不到了，
![描述](http://i1.buimg.com/2f222411f4e51360.png)

**Comment by yangfuhai** [comment]
这个主题还不能用。建议最好是做自己的主题。

**Comment by icnws** [comment]
这个主题还不完善，建议先用默认的，之后熟悉了JPress之后可以改这个东西为自己的
