### ISSUE TITLE
[建议]后台中页面管理

### ISSUE THREAD

**Issue by yuandi0823** [JpressProjects/jpress#30]
@JpressProjects 后台中的**页面管理**不知道你的业务设计意图，在我使用的过程中明显可以用**文章管理**来替代。现在发布入口有两个在使用很容易困惑。
猜测：**页面管理**主要是用来发布单独的不在任何分类，专题下的文章。使用时可以在编辑模板的地方加入相关的**页面**链接地址？？

**Comment by ruyangit** [comment]
page_test.html 当访问http://www.xxx.com/test的时候回调用这个文件渲染。 这个有提到页面这个点，但是新建页面且创建page_test.html 后并没有起作用，请求后返回的结果还是 带有模板的文章页。 @JpressProjects @yuandi0823 该怎么处理呢？
