### ISSUE TITLE
使用NextContentTag和PreviousContentTag标签的问题

### ISSUE THREAD

**Issue by xlbf22** [JpressProjects/jpress#56]
<@jp.next> 
	下一篇：<a href="${content.url}">${content.title}</a>
</@jp.next>
<@jp.previous> 
	上一篇：<a href="${content.url}">${content.title}</a>
</@jp.previous>
按照DOC.md介绍的方式，直接将上面两段加入详细容详情页面（content.html的扩展页面content_XXX.html）。但是界面上显示的是【上一篇:<当前文章的标题>】【下一篇:<当前文章的标题>】，点击连接不管上篇下篇跳转的都是当前文章。

**请问：**是不是我的用法不对？这个地方（<@jp.next> 和<@jp.previous>）是不是还需要加入什么参数，我找了整个DOC.md没有找到相关的说明。

**Comment by yuwagery** [comment]
<@jp.next>
下一篇：${next.title}
/@jp.next
<@jp.previous>
上一篇：${previous.title}
/@jp.previous
