### ISSUE TITLE
maven compile 报错 Could not find artifact io.jboot:jboot:jar:1.0-beta5-SNAPSHOT

### ISSUE THREAD

**Issue by ghost** [JpressProjects/jpress#57]
`[INFO] 
[INFO] ------------------------------------------------------------------------
[INFO] Building io.jpress 1.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[WARNING] The POM for io.jboot:jboot:jar:1.0-beta5-SNAPSHOT is missing, no dependency information available
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 0.193 s
[INFO] Finished at: 2017-08-13T14:54:52+08:00
[INFO] Final Memory: 7M/102M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project io.jpress: Could not resolve dependencies for project jpress:io.jpress:jar:1.0-SNAPSHOT: Could not find artifact io.jboot:jboot:jar:1.0-beta5-SNAPSHOT -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException
`
打包报错！！！！

**Comment by jiyangjin** [comment]
我看到在oschina上面有这个版本对应的项目，但是还没加到maven库中，我直接用的1.0-beta4，然后再把EncryptCookieUtils单独拷贝进去

**Comment by jounghu** [comment]
@jiyangjin  我后面在网上找了一个war包，放入docker之后，运行一直说我本地连不上数据库，我其实本地是可以连数据库的，你有联系方式吗？或者与我联系email 1358199510@qq.com，我想跑通这个代码.

**Comment by jiyangjin** [comment]
我已经提交这个问题，待解决
