### ISSUE TITLE
目前（2017-08-31）git上master版本启动有误，使用的是jboot启动？

### ISSUE THREAD

**Issue by junyi5257** [JpressProjects/jpress#61]
目前（2017-08-31）git上master版本，使用的是jboot启动，和使用说明文档中的不一致，提醒下，别再踩坑了，
可以使用git上的alpha分支版本，或者加群讨论。
PPS:等大神更新吧。

**Comment by mamacmm** [comment]
同样的问题，数据库是空的，使用Starter启动，报错，找不到表，安装的步骤没有了？

**Comment by riveryong** [comment]
我把以前版本的数据弄了一份，不过还是缺表，等海哥吧
我的启动也报错：
com.jfinal.plugin.activerecord.ActiveRecordException: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Table 'jpress.category' doesn't exist

**Comment by songlianwei** [comment]
第一步:把那几张表先在数据库建好;
第二步:使用Starter启动,可以启动;
问题:如何打开配置页面?

**Comment by yolinfeng** [comment]
嗯，确实启动报错。。。连开始都没有就报错了。。。
