### ISSUE TITLE
我安装文档的“进入jpress-web目录，执行`mvn package`命令”不能创建war

### ISSUE THREAD

**Issue by xiacat** [JpressProjects/jpress#65]
1. 没有 jpress-web
2. 在idea中执行packing ，出来的是jar
3. 我在pom中  增加 "< p a c k a g i n g> w a r< / p a c k a g i n g>" ，出来的war只有22byte

能否给我（ xiacat@163.com ）一个再清晰一点的指导？

谢谢！

**Comment by haerri** [comment]
感觉这个项目已经凉了

**Comment by jadeball** [comment]
的确没有 jpress-web

**Comment by niewj** [comment]
是的呢，我这个也没呢。

**Comment by ANT-Yang** [comment]
@xiacat 您好，您的问题得到解决了吗，我这边也遇到了同样的问题
