### ISSUE TITLE
什么时候新版本出来呀，不要用maven呀！

### ISSUE THREAD

**Issue by savagejet** [JpressProjects/jpress#7]
现在功能还有不少BUG，权限什么的都没做，感觉还不能使用，请作者尽快完善功能，看好。
强烈建议不要用maven管理项目呀。

**Comment by RobertCool** [comment]
Maven项目结构比较通用。 可以适用各种IDE

**Comment by TingSky** [comment]
@savagejet 举一个不用maven的理由

**Comment by JpressProjects** [comment]
已出maven...
