### ISSUE TITLE
有没有可以预览的网站，看看效果

### ISSUE THREAD

**Issue by Arisono** [JpressProjects/jpress#76]

**Comment by Hfenger** [comment]
http://www.yangfuhai.com/ 感觉海哥真的累 , 源码都在这了 , 想看后台 , 部署一下很难吗?网站效果自己写套模板想怎么样怎么样不知道你要什么效果 , wordpress总归用过吧......麻烦老哥们提建设性意见好不好 , 我个人感觉伸手不好 , 虽然海哥乐于助人

**Comment by JpressProjects** [comment]
www.jpress.io
